# Supporting Materials Inventory

This notebook inventories the planned Supporting Information items.

Goals:
1. Define the compressed SI outline.
2. Map each SI table and figure to source notebooks and source files.
3. Check which source files already exist.
4. Export an SI inventory table for tracking.

This notebook does not generate final SI tables or figures.

In [1]:
from pathlib import Path
import pandas as pd
import numpy as np
from datetime import datetime

# Run this notebook from:
# hydrovoltaic-ml/notebooks/

PROJECT_ROOT = Path("..").resolve()
RESULTS_DIR = PROJECT_ROOT / "results"
DOCS_DIR = PROJECT_ROOT / "docs"
SI_DIR = RESULTS_DIR / "supporting_materials"

SI_DIR.mkdir(parents=True, exist_ok=True)
(SI_DIR / "tables").mkdir(parents=True, exist_ok=True)
(SI_DIR / "figures").mkdir(parents=True, exist_ok=True)
(SI_DIR / "inventory").mkdir(parents=True, exist_ok=True)

print("Project root:", PROJECT_ROOT)
print("Results folder:", RESULTS_DIR)
print("Supporting materials folder:", SI_DIR)
print("Generated:", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

Project root: <REPOSITORY_ROOT>
Results folder: <REPOSITORY_ROOT>\results
Supporting materials folder: <REPOSITORY_ROOT>\results\supporting_materials
Generated: 2026-05-26 14:10:00

In [2]:
si_methods = [
    {
        "section": "S1",
        "title": "Dataset curation, scope definition, and exclusion criteria",
        "purpose": "Define the literature-derived dataset scope and explain why non-galvanic hydrovoltaic records are retained while galvanic, redox-dominant, triboelectric, and osmotic membrane power systems are excluded.",
        "main_text_link": "Dataset construction / Figure 1",
        "source_notebooks": "01_data_cleaning; 02_modeling_phase1_clean; 12_figure1_dataset_overview",
        "status": "planned",
        "notes": "This section should be concise but rigorous because dataset definition is central to the paper."
    },
    {
        "section": "S2",
        "title": "Target construction, unit standardization, and descriptor encoding",
        "purpose": "Explain P_est = Voc Jsc / 4, log(P_est), log(R), unit conversion, categorical encoding, and missing-value handling.",
        "main_text_link": "Methods / Figure 1 / Figure 2",
        "source_notebooks": "02_modeling_phase1_clean; 03_modeling_v7_validation; 12_figure1_dataset_overview",
        "status": "planned",
        "notes": "Detailed descriptor definitions should mainly be placed in Table S1."
    },
    {
        "section": "S3",
        "title": "Machine-learning workflow and model evaluation",
        "purpose": "Describe model families, Model A vs Model B, train/test split, cross-validation, hyperparameter tuning, and metrics.",
        "main_text_link": "Figure 3",
        "source_notebooks": "03_modeling_v7_validation; 04_modeling_phase2_models; 14_figure3_model_comparison",
        "status": "planned",
        "notes": "Use R²_CV, R²_test, RMSE, and MAE notation consistently."
    },
    {
        "section": "S4",
        "title": "Robustness, feature-block ablation, and descriptor interpretation",
        "purpose": "Support model robustness, feature-block ablation, SHAP interpretation, and mechanism-label limitation.",
        "main_text_link": "Figure 3",
        "source_notebooks": "05_modeling_phase2_robustness; 06_interpretable_rules; 07_visualization_support; 14_figure3_model_comparison",
        "status": "planned",
        "notes": "Do not add ordinary one-hot permutation importance unless grouped permutation is implemented."
    },
    {
        "section": "S5",
        "title": "Internal-resistance analysis and statistical testing",
        "purpose": "Define resistance-regime threshold, low-R/high-R split, nonparametric statistical tests, and R-origin analysis.",
        "main_text_link": "Figure 4 / Figure 5",
        "source_notebooks": "08_internal_resistance_analysis; 11_physics_aware_R_descriptor; 15_figure4_resistance_regimes; 16_figure5_R_origin",
        "status": "planned",
        "notes": "Keep cation-level analysis cautious; do not claim universal individual-cation ranking."
    },
    {
        "section": "S6",
        "title": "Explicit descriptor model and virtual design protocol",
        "purpose": "Explain the explicit Elastic Net descriptor model, linear vs polynomial comparison, virtual design grid, and limitations.",
        "main_text_link": "Figure 6",
        "source_notebooks": "09_design_and_descriptor; 10_virtual_design; 11_physics_aware_R_descriptor; 17_figure6_virtual_design",
        "status": "planned",
        "notes": "State clearly that virtual design is descriptor-guided screening, not an experimentally validated recipe."
    },
]

si_methods_df = pd.DataFrame(si_methods)
display(si_methods_df)

,section,title,purpose,main_text_link,source_notebooks,status,notes
0,S1,"Dataset curation, scope definition, and exclus...",Define the literature-derived dataset scope an...,Dataset construction / Figure 1,01_data_cleaning; 02_modeling_phase1_clean; 12...,planned,This section should be concise but rigorous be...
1,S2,"Target construction, unit standardization, and...","Explain P_est = Voc Jsc / 4, log(P_est), log(R...",Methods / Figure 1 / Figure 2,02_modeling_phase1_clean; 03_modeling_v7_valid...,planned,Detailed descriptor definitions should mainly ...
2,S3,Machine-learning workflow and model evaluation,"Describe model families, Model A vs Model B, t...",Figure 3,03_modeling_v7_validation; 04_modeling_phase2_...,planned,"Use R²_CV, R²_test, RMSE, and MAE notation con..."
3,S4,"Robustness, feature-block ablation, and descri...","Support model robustness, feature-block ablati...",Figure 3,05_modeling_phase2_robustness; 06_interpretabl...,planned,Do not add ordinary one-hot permutation import...
4,S5,Internal-resistance analysis and statistical t...,"Define resistance-regime threshold, low-R/high...",Figure 4 / Figure 5,08_internal_resistance_analysis; 11_physics_aw...,planned,Keep cation-level analysis cautious; do not cl...
5,S6,Explicit descriptor model and virtual design p...,Explain the explicit Elastic Net descriptor mo...,Figure 6,09_design_and_descriptor; 10_virtual_design; 1...,planned,State clearly that virtual design is descripto...

In [3]:
si_tables = [
    {
        "item": "Table S1",
        "title": "Full data dictionary and descriptor encoding",
        "purpose": "Define all columns, units, allowed values, transformations, and notes.",
        "source_notebooks": "01_data_cleaning; 02_modeling_phase1_clean; 03_modeling_v7_validation",
        "expected_source_files": "dataset CSV; data dictionary if available",
        "planned_output": "tables/Table_S1_data_dictionary.csv",
        "priority": "must-have",
        "status": "planned",
        "notes": "Most important SI table."
    },
    {
        "item": "Table S2",
        "title": "Dataset scope, inclusion criteria, and excluded system types",
        "purpose": "Document included/excluded device categories and physical rationale.",
        "source_notebooks": "01_data_cleaning; paper outline",
        "expected_source_files": "manual table",
        "planned_output": "tables/Table_S2_scope_exclusion_criteria.csv",
        "priority": "must-have",
        "status": "planned",
        "notes": "Can be manually created from paper logic."
    },
    {
        "item": "Table S3",
        "title": "Dataset summary and reporting completeness",
        "purpose": "Summarize n=159, availability of targets/descriptors, and key category counts.",
        "source_notebooks": "12_figure1_dataset_overview; 18_paper_numbers_summary",
        "expected_source_files": "fig1D_reporting_completeness.csv; fig1C_*_counts.csv",
        "planned_output": "tables/Table_S3_dataset_summary_reporting_completeness.csv",
        "priority": "must-have",
        "status": "planned",
        "notes": "Should match Figure 1C/1D and main text."
    },
    {
        "item": "Table S4",
        "title": "Model hyperparameters and full performance metrics",
        "purpose": "Provide selected hyperparameters and complete performance metrics for all model families.",
        "source_notebooks": "04_modeling_phase2_models; 14_figure3_model_comparison",
        "expected_source_files": "fig3A_tuned_model_comparison.csv; model tuning output CSVs",
        "planned_output": "tables/Table_S4_model_hyperparameters_full_performance.csv",
        "priority": "must-have",
        "status": "planned",
        "notes": "If RMSE/MAE are not exported yet, compute or mark as not available."
    },
    {
        "item": "Table S5",
        "title": "Descriptor augmentation and feature-block ablation results",
        "purpose": "Summarize Model A vs Model B and feature-block ablation.",
        "source_notebooks": "05_modeling_phase2_robustness; 14_figure3_model_comparison",
        "expected_source_files": "fig3B_modelA_modelB_descriptor_augmentation.csv; fig3C_feature_block_ablation.csv",
        "planned_output": "tables/Table_S5_descriptor_augmentation_ablation.csv",
        "priority": "must-have",
        "status": "planned",
        "notes": "Directly supports Figure 3B/3C."
    },
    {
        "item": "Table S6",
        "title": "SHAP descriptor importance ranking",
        "purpose": "Provide full descriptor importance ranking.",
        "source_notebooks": "07_visualization_support; 14_figure3_model_comparison",
        "expected_source_files": "fig3D_SHAP_descriptor_importance.csv",
        "planned_output": "tables/Table_S6_SHAP_descriptor_importance.csv",
        "priority": "must-have",
        "status": "planned",
        "notes": "Keep feature naming consistent with Figure 3D."
    },
    {
        "item": "Table S7",
        "title": "Internal-resistance group statistics and statistical tests",
        "purpose": "Summarize electrolyte, ion type, and structure effects on log(R), including p values.",
        "source_notebooks": "08_internal_resistance_analysis; 16_figure5_R_origin",
        "expected_source_files": "fig5A_inorganic_electrolyte_summary.csv; fig5B_ion_type_summary.csv; fig5C_structure_class_summary.csv; fig5_statistical_tests.csv",
        "planned_output": "tables/Table_S7_internal_resistance_statistics_tests.csv",
        "priority": "must-have",
        "status": "planned",
        "notes": "Can include cation-level caution as a note or appendix row."
    },
    {
        "item": "Table S8",
        "title": "Explicit descriptor model coefficients and virtual design candidates",
        "purpose": "Provide Elastic Net coefficients and top virtual design candidates.",
        "source_notebooks": "10_virtual_design; 11_physics_aware_R_descriptor; 17_figure6_virtual_design",
        "expected_source_files": "coefficient CSVs; virtual design candidate CSVs",
        "planned_output": "tables/Table_S8_coefficients_virtual_design_candidates.csv",
        "priority": "must-have",
        "status": "planned",
        "notes": "Full virtual design table can also be Supplementary Data CSV."
    },
]

si_tables_df = pd.DataFrame(si_tables)
display(si_tables_df)

,item,title,purpose,source_notebooks,expected_source_files,planned_output,priority,status,notes
0,Table S1,Full data dictionary and descriptor encoding,"Define all columns, units, allowed values, tra...",01_data_cleaning; 02_modeling_phase1_clean; 03...,dataset CSV; data dictionary if available,tables/Table_S1_data_dictionary.csv,must-have,planned,Most important SI table.
1,Table S2,"Dataset scope, inclusion criteria, and exclude...",Document included/excluded device categories a...,01_data_cleaning; paper outline,manual table,tables/Table_S2_scope_exclusion_criteria.csv,must-have,planned,Can be manually created from paper logic.
2,Table S3,Dataset summary and reporting completeness,"Summarize n=159, availability of targets/descr...",12_figure1_dataset_overview; 18_paper_numbers_...,fig1D_reporting_completeness.csv; fig1C_*_coun...,tables/Table_S3_dataset_summary_reporting_comp...,must-have,planned,Should match Figure 1C/1D and main text.
3,Table S4,Model hyperparameters and full performance met...,Provide selected hyperparameters and complete ...,04_modeling_phase2_models; 14_figure3_model_co...,fig3A_tuned_model_comparison.csv; model tuning...,tables/Table_S4_model_hyperparameters_full_per...,must-have,planned,"If RMSE/MAE are not exported yet, compute or m..."
4,Table S5,Descriptor augmentation and feature-block abla...,Summarize Model A vs Model B and feature-block...,05_modeling_phase2_robustness; 14_figure3_mode...,fig3B_modelA_modelB_descriptor_augmentation.cs...,tables/Table_S5_descriptor_augmentation_ablati...,must-have,planned,Directly supports Figure 3B/3C.
5,Table S6,SHAP descriptor importance ranking,Provide full descriptor importance ranking.,07_visualization_support; 14_figure3_model_com...,fig3D_SHAP_descriptor_importance.csv,tables/Table_S6_SHAP_descriptor_importance.csv,must-have,planned,Keep feature naming consistent with Figure 3D.
6,Table S7,Internal-resistance group statistics and stati...,"Summarize electrolyte, ion type, and structure...",08_internal_resistance_analysis; 16_figure5_R_...,fig5A_inorganic_electrolyte_summary.csv; fig5B...,tables/Table_S7_internal_resistance_statistics...,must-have,planned,Can include cation-level caution as a note or ...
7,Table S8,Explicit descriptor model coefficients and vir...,Provide Elastic Net coefficients and top virtu...,10_virtual_design; 11_physics_aware_R_descript...,coefficient CSVs; virtual design candidate CSVs,tables/Table_S8_coefficients_virtual_design_ca...,must-have,planned,Full virtual design table can also be Suppleme...

In [4]:
si_figures = [
    {
        "item": "Fig. S1",
        "title": "Dataset composition and target construction checks",
        "purpose": "Supplement Figure 1 with additional composition and target construction checks.",
        "planned_panels": "material class distribution; electrode/electrolyte descriptor distribution; Voc/Jsc distributions; log(P_est) or reported vs estimated power density",
        "source_notebooks": "07_visualization_support; 12_figure1_dataset_overview",
        "expected_source_files": "dataset CSV; fig1C_*; optional target distribution outputs",
        "planned_output_folder": "figures/Fig_S1_dataset_composition_target_checks",
        "priority": "high",
        "status": "planned",
        "notes": "Avoid duplicating Figure 1C exactly."
    },
    {
        "item": "Fig. S2",
        "title": "Model validation and prediction behavior",
        "purpose": "Show predicted-vs-observed and residual behavior.",
        "planned_panels": "predicted vs observed for linear model; predicted vs observed for tree/boosting model; residual distribution; residual vs predicted",
        "source_notebooks": "04_modeling_phase2_models; 07_visualization_support",
        "expected_source_files": "model prediction outputs if available",
        "planned_output_folder": "figures/Fig_S2_model_validation_prediction_behavior",
        "priority": "high",
        "status": "planned",
        "notes": "Supports the claim that models are descriptor-discovery tools, not perfect predictors."
    },
    {
        "item": "Fig. S3",
        "title": "Robustness of model conclusions",
        "purpose": "Support robustness under repeated split, grouped validation, target sensitivity, and subgroup modeling.",
        "planned_panels": "repeated split performance; grouped CV/paper-level validation; target sensitivity; mechanism subgroup modeling",
        "source_notebooks": "05_modeling_phase2_robustness",
        "expected_source_files": "robustness output CSVs",
        "planned_output_folder": "figures/Fig_S3_model_robustness",
        "priority": "high",
        "status": "planned",
        "notes": "Do not over-expand. Use only the strongest robustness evidence."
    },
    {
        "item": "Fig. S4",
        "title": "Extended descriptor interpretation",
        "purpose": "Provide full SHAP and descriptor interpretation beyond main Figure 3.",
        "planned_panels": "full SHAP ranking; model-family SHAP comparison if available; log(R) dependence or descriptor association; mechanism-label limitation",
        "source_notebooks": "07_visualization_support; 14_figure3_model_comparison",
        "expected_source_files": "fig3D_SHAP_descriptor_importance.csv; association/interpretation outputs",
        "planned_output_folder": "figures/Fig_S4_extended_descriptor_interpretation",
        "priority": "medium-high",
        "status": "planned",
        "notes": "No ordinary one-hot permutation importance."
    },
    {
        "item": "Fig. S5",
        "title": "Resistance-regime sensitivity and internal-resistance origin",
        "purpose": "Support threshold choice, R descriptor comparison, and origin of R.",
        "planned_panels": "threshold sensitivity; raw log(R) vs centered log(R) vs R-regime descriptor; R-as-target model performance; cation/electrolyte-level R analysis",
        "source_notebooks": "06_interpretable_rules; 08_internal_resistance_analysis; 11_physics_aware_R_descriptor; 15_figure4_resistance_regimes; 16_figure5_R_origin",
        "expected_source_files": "fig4D descriptor comparison; Fig.5 summary/test CSVs; R-analysis outputs",
        "planned_output_folder": "figures/Fig_S5_R_regime_sensitivity_R_origin",
        "priority": "high",
        "status": "planned",
        "notes": "This is the key SI figure connecting Figure 4 and Figure 5."
    },
    {
        "item": "Fig. S6",
        "title": "Explicit descriptor model and virtual design details",
        "purpose": "Support Figure 6 with diagnostics and full virtual design landscape.",
        "planned_panels": "full coefficient plot; predicted vs observed for explicit model; virtual design landscape; ranked candidates",
        "source_notebooks": "09_design_and_descriptor; 10_virtual_design; 11_physics_aware_R_descriptor; 17_figure6_virtual_design",
        "expected_source_files": "coefficient CSVs; model comparison CSVs; virtual design CSVs",
        "planned_output_folder": "figures/Fig_S6_descriptor_model_virtual_design",
        "priority": "high",
        "status": "planned",
        "notes": "State that virtual design is screening, not validated recipe."
    },
]

si_figures_df = pd.DataFrame(si_figures)
display(si_figures_df)

,item,title,purpose,planned_panels,source_notebooks,expected_source_files,planned_output_folder,priority,status,notes
0,Fig. S1,Dataset composition and target construction ch...,Supplement Figure 1 with additional compositio...,material class distribution; electrode/electro...,07_visualization_support; 12_figure1_dataset_o...,dataset CSV; fig1C_*; optional target distribu...,figures/Fig_S1_dataset_composition_target_checks,high,planned,Avoid duplicating Figure 1C exactly.
1,Fig. S2,Model validation and prediction behavior,Show predicted-vs-observed and residual behavior.,predicted vs observed for linear model; predic...,04_modeling_phase2_models; 07_visualization_su...,model prediction outputs if available,figures/Fig_S2_model_validation_prediction_beh...,high,planned,Supports the claim that models are descriptor-...
2,Fig. S3,Robustness of model conclusions,"Support robustness under repeated split, group...",repeated split performance; grouped CV/paper-l...,05_modeling_phase2_robustness,robustness output CSVs,figures/Fig_S3_model_robustness,high,planned,Do not over-expand. Use only the strongest rob...
3,Fig. S4,Extended descriptor interpretation,Provide full SHAP and descriptor interpretatio...,full SHAP ranking; model-family SHAP compariso...,07_visualization_support; 14_figure3_model_com...,fig3D_SHAP_descriptor_importance.csv; associat...,figures/Fig_S4_extended_descriptor_interpretation,medium-high,planned,No ordinary one-hot permutation importance.
4,Fig. S5,Resistance-regime sensitivity and internal-res...,"Support threshold choice, R descriptor compari...",threshold sensitivity; raw log(R) vs centered ...,06_interpretable_rules; 08_internal_resistance...,fig4D descriptor comparison; Fig.5 summary/tes...,figures/Fig_S5_R_regime_sensitivity_R_origin,high,planned,This is the key SI figure connecting Figure 4 ...
5,Fig. S6,Explicit descriptor model and virtual design d...,Support Figure 6 with diagnostics and full vir...,full coefficient plot; predicted vs observed f...,09_design_and_descriptor; 10_virtual_design; 1...,coefficient CSVs; model comparison CSVs; virtu...,figures/Fig_S6_descriptor_model_virtual_design,high,planned,"State that virtual design is screening, not va..."

In [5]:
# Scan existing result files
file_records = []

for p in RESULTS_DIR.rglob("*"):
    if p.is_file() and p.suffix.lower() in [".csv", ".xlsx", ".pdf", ".png", ".svg", ".html", ".txt"]:
        file_records.append({
            "file_name": p.name,
            "suffix": p.suffix.lower(),
            "relative_path": str(p.relative_to(PROJECT_ROOT)),
            "parent_folder": str(p.parent.relative_to(PROJECT_ROOT)),
            "size_kb": round(p.stat().st_size / 1024, 1),
        })

source_files_df = pd.DataFrame(file_records)

print("Number of result files found:", len(source_files_df))
display(source_files_df.sort_values(["parent_folder", "file_name"]).head(50))

Number of result files found: 137

,file_name,suffix,relative_path,parent_folder,size_kb
0,09_descriptor_model_comparison.csv,.csv,results\09_descriptor_model_comparison.csv,results,0.4
1,09_elastic_net_descriptor_coefficients.csv,.csv,results\09_elastic_net_descriptor_coefficients...,results,0.6
2,09_polynomial_elastic_net_descriptor_coefficie...,.csv,results\09_polynomial_elastic_net_descriptor_c...,results,0.7
3,10_virtual_design_cases.csv,.csv,results\10_virtual_design_cases.csv,results,0.9
6,11_R_regime_performance_summary.csv,.csv,results\11_R_regime_performance_summary.csv,results,0.2
4,11_best_physics_R_descriptor_coefficients.csv,.csv,results\11_best_physics_R_descriptor_coefficie...,results,0.6
5,11_physics_R_descriptor_model_comparison.csv,.csv,results\11_physics_R_descriptor_model_comparis...,results,0.6
7,11_structure_R_regime_summary.csv,.csv,results\11_structure_R_regime_summary.csv,results,0.6
8,ablation_summary.csv,.csv,results\ablation_summary.csv,results,0.8
12,phase2_R_descriptor_summary.csv,.csv,results\phase2_R_descriptor_summary.csv,results,0.2
9,phase2_mechanism_subgroup_results.csv,.csv,results\phase2_mechanism_subgroup_results.csv,results,0.2
10,phase2_predicted_vs_true_summary.csv,.csv,results\phase2_predicted_vs_true_summary.csv,results,0.3
11,phase2_rule_tree_regime_summary.csv,.csv,results\phase2_rule_tree_regime_summary.csv,results,0.2
13,phase2_simplified_rule_summary.csv,.csv,results\phase2_simplified_rule_summary.csv,results,0.4
14,phase2_structure_R_descriptor_summary.csv,.csv,results\phase2_structure_R_descriptor_summary.csv,results,0.8
15,phase2_structure_R_descriptor_summary_filtered...,.csv,results\phase2_structure_R_descriptor_summary_...,results,0.6
16,phase2_structure_R_regime_summary.csv,.csv,results\phase2_structure_R_regime_summary.csv,results,0.8
17,phase2_tuned_best_params.csv,.csv,results\phase2_tuned_best_params.csv,results,0.4
18,subgroup_summary.csv,.csv,results\subgroup_summary.csv,results,0.1
19,fig1C_ion_type_counts.csv,.csv,results\figure1_dataset_overview\fig1C_ion_typ...,results\figure1_dataset_overview,0.1
20,fig1C_log_P_est_histogram_bins.csv,.csv,results\figure1_dataset_overview\fig1C_log_P_e...,results\figure1_dataset_overview,0.9
21,fig1C_log_P_est_raw.csv,.csv,results\figure1_dataset_overview\fig1C_log_P_e...,results\figure1_dataset_overview,3.2
22,fig1C_mechanism_counts.csv,.csv,results\figure1_dataset_overview\fig1C_mechani...,results\figure1_dataset_overview,0.1
23,fig1C_structure_counts.csv,.csv,results\figure1_dataset_overview\fig1C_structu...,results\figure1_dataset_overview,0.2
24,fig1D_reporting_completeness.csv,.csv,results\figure1_dataset_overview\fig1D_reporti...,results\figure1_dataset_overview,0.5
131,fig1C_final_dataset_composition_and_target_dis...,.pdf,results\figure1_dataset_overview\final_panels\...,results\figure1_dataset_overview\final_panels,38.2
132,fig1C_final_dataset_composition_and_target_dis...,.png,results\figure1_dataset_overview\final_panels\...,results\figure1_dataset_overview\final_panels,308.3
133,fig1C_final_dataset_composition_and_target_dis...,.svg,results\figure1_dataset_overview\final_panels\...,results\figure1_dataset_overview\final_panels,33.8
134,fig1D_final_reporting_completeness.pdf,.pdf,results\figure1_dataset_overview\final_panels\...,results\figure1_dataset_overview\final_panels,29.2
135,fig1D_final_reporting_completeness.png,.png,results\figure1_dataset_overview\final_panels\...,results\figure1_dataset_overview\final_panels,177.0
136,fig1D_final_reporting_completeness.svg,.svg,results\figure1_dataset_overview\final_panels\...,results\figure1_dataset_overview\final_panels,12.0
25,fig2A_mechanism_vs_logPest.csv,.csv,results\figure2_dataset_structure\fig2A_mechan...,results\figure2_dataset_structure,5.1
26,fig2B_structure_vs_logPest.csv,.csv,results\figure2_dataset_structure\fig2B_struct...,results\figure2_dataset_structure,4.3
27,fig2C_iontype_vs_logPest.csv,.csv,results\figure2_dataset_structure\fig2C_iontyp...,results\figure2_dataset_structure,4.6
28,fig2D_descriptor_association_heatmap.csv,.csv,results\figure2_dataset_structure\fig2D_descri...,results\figure2_dataset_structure,1.3
29,fig2D_descriptor_association_table.csv,.csv,results\figure2_dataset_structure\fig2D_descri...,results\figure2_dataset_structure,0.4
119,fig2A_final_mechanism_label_vs_performance.pdf,.pdf,results\figure2_dataset_structure\final_panels...,results\figure2_dataset_structure\final_panels,33.9
120,fig2A_final_mechanism_label_vs_performance.png,.png,results\figure2_dataset_structure\final_panels...,results\figure2_dataset_structure\final_panels,144.0
121,fig2A_final_mechanism_label_vs_performance.svg,.svg,results\figure2_dataset_structure\final_panels...,results\figure2_dataset_structure\final_panels,35.9
122,fig2B_final_structure_class_vs_performance.pdf,.pdf,results\figure2_dataset_structure\final_panels...,results\figure2_dataset_structure\final_panels,35.4
123,fig2B_final_structure_class_vs_performance.png,.png,results\figure2_dataset_structure\final_panels...,results\figure2_dataset_structure\final_panels,182.2
124,fig2B_final_structure_class_vs_performance.svg,.svg,results\figure2_dataset_structure\final_panels...,results\figure2_dataset_structure\final_panels,43.1
125,fig2C_final_ion_type_vs_performance.pdf,.pdf,results\figure2_dataset_structure\final_panels...,results\figure2_dataset_structure\final_panels,34.6
126,fig2C_final_ion_type_vs_performance.png,.png,results\figure2_dataset_structure\final_panels...,results\figure2_dataset_structure\final_panels,137.1
127,fig2C_final_ion_type_vs_performance.svg,.svg,results\figure2_dataset_structure\final_panels...,results\figure2_dataset_structure\final_panels,38.4
128,fig2D_final_descriptor_association_map.pdf,.pdf,results\figure2_dataset_structure\final_panels...,results\figure2_dataset_structure\final_panels,52.1
129,fig2D_final_descriptor_association_map.png,.png,results\figure2_dataset_structure\final_panels...,results\figure2_dataset_structure\final_panels,338.5
130,fig2D_final_descriptor_association_map.svg,.svg,results\figure2_dataset_structure\final_panels...,results\figure2_dataset_structure\final_panels,41.8
30,fig3A_tuned_model_comparison.csv,.csv,results\figure3_model_comparison\fig3A_tuned_m...,results\figure3_model_comparison,0.1
31,fig3B_modelA_modelB_descriptor_augmentation.csv,.csv,results\figure3_model_comparison\fig3B_modelA_...,results\figure3_model_comparison,0.2

In [6]:
expected_files = [
    # Figure 1 / dataset summary
    "results/figure1_dataset_overview/fig1C_mechanism_counts.csv",
    "results/figure1_dataset_overview/fig1C_structure_counts.csv",
    "results/figure1_dataset_overview/fig1C_ion_type_counts.csv",
    "results/figure1_dataset_overview/fig1C_log_P_est_histogram_bins.csv",
    "results/figure1_dataset_overview/fig1D_reporting_completeness.csv",

    # Figure 3 / model comparison
    "results/figure3_model_comparison/fig3A_tuned_model_comparison.csv",
    "results/figure3_model_comparison/fig3B_modelA_modelB_descriptor_augmentation.csv",
    "results/figure3_model_comparison/fig3C_feature_block_ablation.csv",
    "results/figure3_model_comparison/fig3D_SHAP_descriptor_importance.csv",

    # Figure 4 / R regimes
    "results/figure4_resistance_regimes/fig4A_logR_vs_logPest_raw.csv",
    "results/figure4_resistance_regimes/fig4A_logR_vs_logPest_binned_trend.csv",
    "results/figure4_resistance_regimes/fig4B_R_regime_raw.csv",
    "results/figure4_resistance_regimes/fig4B_R_regime_summary.csv",
    "results/figure4_resistance_regimes/fig4D_R_descriptor_comparison.csv",
    "results/figure4_resistance_regimes/fig4D_physics_aware_R_descriptor_comparison.csv",

    # Figure 5 / R origin
    "results/figure5_R_origin/fig5_raw_observed_R_data.csv",
    "results/figure5_R_origin/fig5A_inorganic_electrolyte_summary.csv",
    "results/figure5_R_origin/fig5B_ion_type_summary.csv",
    "results/figure5_R_origin/fig5C_structure_class_summary.csv",
    "results/figure5_R_origin/fig5_statistical_tests.csv",

    # Figure 6 / descriptor model and virtual design
    "results/figure6_virtual_design/fig6A_linear_descriptor_coefficients_plot.csv",
    "results/figure6_virtual_design/fig6B_linear_vs_polynomial_model_comparison.csv",
    "results/figure6_virtual_design/fig6C_regime_aware_virtual_design.csv",
    "results/figure6_virtual_design/fig6D_top_virtual_design_candidates.csv",
]

expected_file_rows = []

for rel in expected_files:
    p = PROJECT_ROOT / rel
    expected_file_rows.append({
        "relative_path": rel,
        "exists": p.exists(),
        "size_kb": round(p.stat().st_size / 1024, 1) if p.exists() else np.nan,
    })

expected_files_df = pd.DataFrame(expected_file_rows)

display(expected_files_df)

missing_files_df = expected_files_df.loc[~expected_files_df["exists"]].copy()

print("Missing expected files:", len(missing_files_df))
display(missing_files_df)

                                        relative_path  exists  size_kb
0   results/figure1_dataset_overview/fig1C_mechani...    True      0.1
1   results/figure1_dataset_overview/fig1C_structu...    True      0.2
2   results/figure1_dataset_overview/fig1C_ion_typ...    True      0.1
3   results/figure1_dataset_overview/fig1C_log_P_e...    True      0.9
4   results/figure1_dataset_overview/fig1D_reporti...    True      0.5
5   results/figure3_model_comparison/fig3A_tuned_m...    True      0.1
6   results/figure3_model_comparison/fig3B_modelA_...    True      0.2
7   results/figure3_model_comparison/fig3C_feature...    True      0.3
8   results/figure3_model_comparison/fig3D_SHAP_de...    True      0.3
9   results/figure4_resistance_regimes/fig4A_logR_...    True      6.1
10  results/figure4_resistance_regimes/fig4A_logR_...    True      0.9
11  results/figure4_resistance_regimes/fig4B_R_reg...    True      4.6
12  results/figure4_resistance_regimes/fig4B_R_reg...    True      0.3
13  results/figure4_resistance_regimes/fig4D_R_des...    True      0.2
14  results/figure4_resistance_regimes/fig4D_physi...    True      0.2
15  results/figure5_R_origin/fig5_raw_observed_R_d...    True      6.8
16  results/figure5_R_origin/fig5A_inorganic_elect...    True      0.3
17  results/figure5_R_origin/fig5B_ion_type_summar...    True      0.3
18  results/figure5_R_origin/fig5C_structure_class...    True      0.5
19  results/figure5_R_origin/fig5_statistical_test...    True      0.3
20  results/figure6_virtual_design/fig6A_linear_de...    True      0.9
21  results/figure6_virtual_design/fig6B_linear_vs...    True      0.6
22  results/figure6_virtual_design/fig6C_regime_aw...    True      0.9
23  results/figure6_virtual_design/fig6D_top_virtu...    True      0.6

Missing expected files: 0

Empty DataFrame
Columns: [relative_path, exists, size_kb]
Index: []

In [7]:
def status_from_notes(text, expected_files_df):
    """
    Lightweight status helper.
    This does not fully validate scientific content;
    it only checks whether likely result files exist.
    """
    text = str(text).lower()

    if "manual table" in text:
        return "manual_creation_needed"

    keywords = []
    if "fig1" in text:
        keywords.append("figure1_dataset_overview")
    if "fig3" in text:
        keywords.append("figure3_model_comparison")
    if "fig4" in text:
        keywords.append("figure4_resistance_regimes")
    if "fig5" in text:
        keywords.append("figure5_R_origin")
    if "fig6" in text:
        keywords.append("figure6_virtual_design")

    if not keywords:
        return "source_check_needed"

    mask = expected_files_df["relative_path"].str.contains("|".join(keywords), case=False, regex=True)
    subset = expected_files_df.loc[mask]

    if len(subset) == 0:
        return "source_check_needed"
    elif subset["exists"].all():
        return "source_files_found"
    elif subset["exists"].any():
        return "partial_source_files_found"
    else:
        return "source_files_missing"


si_tables_df["source_file_status"] = si_tables_df["expected_source_files"].apply(
    lambda x: status_from_notes(x, expected_files_df)
)

si_figures_df["source_file_status"] = si_figures_df["expected_source_files"].apply(
    lambda x: status_from_notes(x, expected_files_df)
)

display(si_tables_df[["item", "title", "priority", "source_file_status", "notes"]])
display(si_figures_df[["item", "title", "priority", "source_file_status", "notes"]])

,item,title,priority,source_file_status,notes
0,Table S1,Full data dictionary and descriptor encoding,must-have,source_check_needed,Most important SI table.
1,Table S2,"Dataset scope, inclusion criteria, and exclude...",must-have,manual_creation_needed,Can be manually created from paper logic.
2,Table S3,Dataset summary and reporting completeness,must-have,source_files_found,Should match Figure 1C/1D and main text.
3,Table S4,Model hyperparameters and full performance met...,must-have,source_files_found,"If RMSE/MAE are not exported yet, compute or m..."
4,Table S5,Descriptor augmentation and feature-block abla...,must-have,source_files_found,Directly supports Figure 3B/3C.
5,Table S6,SHAP descriptor importance ranking,must-have,source_files_found,Keep feature naming consistent with Figure 3D.
6,Table S7,Internal-resistance group statistics and stati...,must-have,source_files_found,Can include cation-level caution as a note or ...
7,Table S8,Explicit descriptor model coefficients and vir...,must-have,source_check_needed,Full virtual design table can also be Suppleme...

,item,title,priority,source_file_status,notes
0,Fig. S1,Dataset composition and target construction ch...,high,source_files_found,Avoid duplicating Figure 1C exactly.
1,Fig. S2,Model validation and prediction behavior,high,source_check_needed,Supports the claim that models are descriptor-...
2,Fig. S3,Robustness of model conclusions,high,source_check_needed,Do not over-expand. Use only the strongest rob...
3,Fig. S4,Extended descriptor interpretation,medium-high,source_files_found,No ordinary one-hot permutation importance.
4,Fig. S5,Resistance-regime sensitivity and internal-res...,high,source_files_found,This is the key SI figure connecting Figure 4 ...
5,Fig. S6,Explicit descriptor model and virtual design d...,high,source_check_needed,"State that virtual design is screening, not va..."

In [8]:
key_numbers = [
    {
        "quantity": "Final dataset records",
        "value": 159,
        "unit": "records",
        "source": "Figure 1 / paper_numbers_summary",
        "used_in": "Main text; Table S3; Fig. 1",
        "check_status": "locked",
    },
    {
        "quantity": "Internal resistance available",
        "value": "112/159",
        "unit": "records",
        "source": "Figure 1D / Figure 4",
        "used_in": "Main text; Table S3; Fig. 4; Fig. 5",
        "check_status": "locked",
    },
    {
        "quantity": "Reported power density available",
        "value": "108/159",
        "unit": "records",
        "source": "Figure 1D",
        "used_in": "Main text; Table S3",
        "check_status": "locked",
    },
    {
        "quantity": "R-regime threshold",
        "value": -1.0,
        "unit": "log(R), R in MΩ",
        "source": "Figure 4",
        "used_in": "Main text; Fig. 4; Fig. 5; Table S11/S7",
        "check_status": "locked",
    },
    {
        "quantity": "Low-R records",
        "value": 55,
        "unit": "records",
        "source": "Figure 4B",
        "used_in": "Main text; Table S7/S11",
        "check_status": "locked",
    },
    {
        "quantity": "High-R records",
        "value": 57,
        "unit": "records",
        "source": "Figure 4B",
        "used_in": "Main text; Table S7/S11",
        "check_status": "locked",
    },
    {
        "quantity": "Low-R median log(P_est)",
        "value": 0.455,
        "unit": "log(μW cm−2)",
        "source": "Figure 4B",
        "used_in": "Main text; Table S7/S11",
        "check_status": "locked",
    },
    {
        "quantity": "High-R median log(P_est)",
        "value": -0.824,
        "unit": "log(μW cm−2)",
        "source": "Figure 4B",
        "used_in": "Main text; Table S7/S11",
        "check_status": "locked",
    },
    {
        "quantity": "R-regime descriptor R²_CV",
        "value": 0.297,
        "unit": "R²_CV",
        "source": "Figure 4C / former Figure 4D",
        "used_in": "Main text; Fig. 4; Fig. S5",
        "check_status": "locked",
    },
    {
        "quantity": "Linear explicit descriptor model R²_CV",
        "value": "0.298 ± 0.134",
        "unit": "R²_CV",
        "source": "Figure 6B",
        "used_in": "Main text; Fig. 6; Fig. S6",
        "check_status": "locked",
    },
    {
        "quantity": "Top virtual design predicted log(P_est)",
        "value": 1.794,
        "unit": "log(μW cm−2)",
        "source": "Figure 6D",
        "used_in": "Main text; Table S8; Fig. S6",
        "check_status": "locked",
    },
]

key_numbers_df = pd.DataFrame(key_numbers)
display(key_numbers_df)

,quantity,value,unit,source,used_in,check_status
0,Final dataset records,159,records,Figure 1 / paper_numbers_summary,Main text; Table S3; Fig. 1,locked
1,Internal resistance available,112/159,records,Figure 1D / Figure 4,Main text; Table S3; Fig. 4; Fig. 5,locked
2,Reported power density available,108/159,records,Figure 1D,Main text; Table S3,locked
3,R-regime threshold,-1.0,"log(R), R in MΩ",Figure 4,Main text; Fig. 4; Fig. 5; Table S11/S7,locked
4,Low-R records,55,records,Figure 4B,Main text; Table S7/S11,locked
5,High-R records,57,records,Figure 4B,Main text; Table S7/S11,locked
6,Low-R median log(P_est),0.455,log(μW cm−2),Figure 4B,Main text; Table S7/S11,locked
7,High-R median log(P_est),-0.824,log(μW cm−2),Figure 4B,Main text; Table S7/S11,locked
8,R-regime descriptor R²_CV,0.297,R²_CV,Figure 4C / former Figure 4D,Main text; Fig. 4; Fig. S5,locked
9,Linear explicit descriptor model R²_CV,0.298 ± 0.134,R²_CV,Figure 6B,Main text; Fig. 6; Fig. S6,locked
10,Top virtual design predicted log(P_est),1.794,log(μW cm−2),Figure 6D,Main text; Table S8; Fig. S6,locked

In [9]:
inventory_dir = SI_DIR / "inventory"
inventory_dir.mkdir(parents=True, exist_ok=True)

# Export individual CSV files
si_methods_df.to_csv(inventory_dir / "SI_methods_inventory.csv", index=False, encoding="utf-8-sig")
si_tables_df.to_csv(inventory_dir / "SI_tables_inventory.csv", index=False, encoding="utf-8-sig")
si_figures_df.to_csv(inventory_dir / "SI_figures_inventory.csv", index=False, encoding="utf-8-sig")
expected_files_df.to_csv(inventory_dir / "SI_expected_files_check.csv", index=False, encoding="utf-8-sig")
source_files_df.to_csv(inventory_dir / "SI_existing_result_files.csv", index=False, encoding="utf-8-sig")
key_numbers_df.to_csv(inventory_dir / "SI_key_numbers_checklist.csv", index=False, encoding="utf-8-sig")

# Export combined Excel workbook if openpyxl is available
xlsx_path = inventory_dir / "SI_outline_inventory.xlsx"

try:
    with pd.ExcelWriter(xlsx_path, engine="openpyxl") as writer:
        si_methods_df.to_excel(writer, sheet_name="Methods", index=False)
        si_tables_df.to_excel(writer, sheet_name="Tables", index=False)
        si_figures_df.to_excel(writer, sheet_name="Figures", index=False)
        expected_files_df.to_excel(writer, sheet_name="Expected files", index=False)
        missing_files_df.to_excel(writer, sheet_name="Missing files", index=False)
        key_numbers_df.to_excel(writer, sheet_name="Key numbers", index=False)
        source_files_df.to_excel(writer, sheet_name="Existing result files", index=False)

    print("Exported Excel inventory:")
    print(xlsx_path)

except Exception as e:
    print("Excel export skipped or failed:")
    print(e)
    print("CSV files were still exported.")

print("\nExported CSV files:")
for p in sorted(inventory_dir.glob("SI_*.csv")):
    print(" -", p.name)

Exported Excel inventory:
<REPOSITORY_ROOT>\results\supporting_materials\inventory\SI_outline_inventory.xlsx

Exported CSV files:
 - SI_existing_result_files.csv
 - SI_expected_files_check.csv
 - SI_figures_inventory.csv
 - SI_key_numbers_checklist.csv
 - SI_methods_inventory.csv
 - SI_tables_inventory.csv

In [10]:
print("Supporting Materials inventory summary")
print("--------------------------------------")
print("Methods sections:", len(si_methods_df))
print("Supplementary tables:", len(si_tables_df))
print("Supplementary figures:", len(si_figures_df))
print("Expected files checked:", len(expected_files_df))
print("Missing expected files:", len(missing_files_df))
print("Key numbers tracked:", len(key_numbers_df))

if len(missing_files_df) > 0:
    print("\nMissing files that may need re-export:")
    display(missing_files_df)
else:
    print("\nAll expected key files were found.")

Supporting Materials inventory summary
--------------------------------------
Methods sections: 6
Supplementary tables: 8
Supplementary figures: 6
Expected files checked: 24
Missing expected files: 0
Key numbers tracked: 11

All expected key files were found.